# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.




    <!-- Select Chicken Type -->
    <label for="chickenType">Select Chicken Type:</label>
    <select id="chickenType" name="chickenType" required>
        <option value="rhode_island_red">Rhode Island Red</option>
        <option value="leghorn">Leghorn</option>
        <option value="plymouth_rock">Plymouth Rock</option>
    </select>
    <br><br>
    
    <!-- Select Number of Eggs -->
    <label for="numEggs">Number of Eggs:</label>
    <input type="number" id="numEggs" name="numEggs" min="1" required>
    <br><br>
    
    <!-- Select Pickup Date -->
    <label for="pickupDate">Pickup Date:</label>
    <input type="date" id="pickupDate" name="pickupDate" required>
    <br><br>
    
    <!-- Select Payment Method -->
    <label for="paymentMethod">Payment Method:</label>
    <select id="paymentMethod" name="paymentMethod" required>
        <option value="cash">Cash</option>
        <option value="credit_card">Credit Card</option>
        <option value="paypal">PayPal</option>
    </select>
    <br><br>
    
    <!-- Submit Form -->
    <button type="submit">Place Order</button>
</form>
